export interface Movement {
    numero_recibo: number | string;
    cod_contribuinte: number | string;
    nome_contribuinte: string;
    end_logradouro: string;
    end_numero: number | string;
    end_complemento: string;
    end_referencia: string;
    end_municipio: string;
    end_bairro: string;
    telefone1: string;
    telefone2: string;
    telefone3: string;
    memo_obs_mensageiro: string; 
    usuario_baixa: string; 
    valor_prev: string | number;
    valor_pago: string | number;
    cod_banco_baixa: number | string;
    cod_tipo_pagamento: number | string;
    data_ultima_contribuicoes: Date;
    cod_ultima_ocorrencia: number | string;
    status: number | string;
    operador: string;
    data_prev: Date;
    turno: string;
    ordem: number | null;
    saldos: string | number;
    doador_novo: boolean;
    texto_obs: string;
    ultima_visita: Date | null | string;
    latitude: string | null;
    longitude: string | null;
    distancia: string;
    data_baixa: Date | null | string;
    obs_contribuinte: string;
    CPF: string | number;
    CNPJ: string | number;
    TipoPessoa: string | number;
  }